### ISSUE TITLE
Mixed Dtypes warning when generating timetables

### ISSUE THREAD

**Issue by spencer-b-318** [department-for-transport-BODS/bods-data-extractor#22]
Console output warns columns have mixed types after "Calling Naptan API to get lat/lon for each stop... " and before "Generating timetable"

1. set stop_level = True
2. run for any number of datasets
3. See error in console
4. code example:

```python
timetable_ = TimetableExtractor(api_key=api # Your API Key Here
                                 ,limit=1 # How many datasets to view
                                 ,status = 'published' # Only view published datasets
                                 ,service_line_level=True # True if you require Service line data 
                                 ,stop_level=True # True if you require stop level data

                               )
```

Expect to see no warnings/errors on timetable generation

**Screenshots**

![image](https://user-images.githubusercontent.com/105863784/202723420-60527cb8-eb85-4fed-b8a4-bb9c4f73a767.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: Pycharm

**Comment by EOstridge** [comment]
We discussed the suggested fix using low_memory=False and the alternative to set each of the data types on import. We decided it was best to move forward with the low_memory=False fix as the difference in performance was not noticeable when testing and this suppresses the dtype warning.

**Comment by lldwork** [comment]
there is a third alternative solution - low_memory=False not necessarily best practice. Was testing done with full dataset? dtype does take longer but it allows you to easily spot incorrect data - just be aware why the dtype occurs (file is split into chunks for processing when low_memory=True, if one chunk has all integers for one column and another has strings with mix of numbers and letters, you will get the dtype error.

**Comment by spencer-b-318** [comment]
Recommendation from @lldwork is to not suppress the error, kicking it down the line. Instead to format the columns correctly (only 4 of them) using column dtype. Should be low effort.
