### ISSUE TITLE
User should know why API request has returned no data

### ISSUE THREAD

**Issue by spencer-b-318** [department-for-transport-BODS/bods-data-extractor#24]
**Is your feature request related to a problem? Please describe.**
If the API request sent by TimetableExtractor returns nothing, KeyError: 'results' is raised. This error does not provide much information to the user as to why the request has returned nothing. It could be due to no data found in the database or it could be due to invalid API key. Better error handling would improve this experience.

**Describe the solution you'd like**
A bespoke exception could be the solution, returns the API response if not '200 OK'. If API response is valid, then suggest a reason for the failure.

**Describe alternatives you've considered**
TimetableExtractor could simply print API response but this would not cover cases where invalid search terms such as NOC have been used

Here, api_key = 0 has been passed, resulting in 403 response but this is not shown to the user

![image](https://user-images.githubusercontent.com/105863784/202754955-52ae47a3-d4e5-4c2f-8c90-d2fc0f11076e.png)

**Comment by adamakram1** [comment]
![image](https://user-images.githubusercontent.com/114913914/210807795-8f3ca51f-428b-403c-9cfa-9b8f7e02e4c4.png)
The status code and reason are displayed when there's an incorrect API response

**Comment by spencer-b-318** [comment]
@adamakram1 this is better, but the error is ultimately still always going to be `Key Error: 'results` which is confusing. 

I was thinking we create a custom exception class. This would also be able to catch a 200 status code with no data

**Comment by adamakram1** [comment]
![image](https://user-images.githubusercontent.com/114913914/210819227-47661dba-16d1-4e6b-8b4b-5a4c3140ddda.png)
Amended the original solution so that the error handling takes place in another class

**Comment by adamakram1** [comment]
![image](https://user-images.githubusercontent.com/114913914/210847536-0c13176c-8241-4e9b-be6a-d5db3355c01e.png)
Tested on empty datasets and when setting limit to 0

**Comment by lldwork** [comment]
does the custom Error class import from standard Error classes?

**Comment by adamakram1** [comment]
Hi, we have decided not to go ahead with the current approach with a custom error class. Instead we are raising an actual error which will help us trace back lines in debugging. The new approach can be viewed in the pull requests:

https://github.com/department-for-transport-BODS/bods-data-extractor/pull/49

**Comment by adamakram1** [comment]
Leave a more specific message with regards to why we have an empty dataset, e.g NOCS
