### ISSUE TITLE
Bug with 'ATCO_code_to_LA_lookup.csv' file mapping to null ATCO codes and admin area's

### ISSUE THREAD

**Issue by isrirai1** [department-for-transport-BODS/bods-data-extractor#26]
**Describe the bug**
Where there are null values in the 'ATCO_code_to_LA_lookup.csv', these are being mapped incorrectly to a service. This is resulting in confusion when determining whether a service is in BODS or not.

**To Reproduce**
1. Method 'services_on_bods_or_otc_by_area()' is for some services showing incorrect admin areas. 

**Expected behavior**
Auth descriptions/ATCO codes should correctly match to the 'ATCO_code_to_LA_lookup.csv'.
To deal with issue, rows with null values have been removed from the 'ATCO_code_to_LA_lookup.csv' file.

**Screenshots**

**Desktop (please complete the following information):**
 ALL

**Smartphone (please complete the following information):**
 ALL

**Comment by lldwork** [comment]
not sure this fix is sustainable - does LA to ATCO never change?

**Comment by spencer-b-318** [comment]
Note for future table - raise an error if blank ATCO code found

**Comment by adamakram1** [comment]
Create an additional ticket
