### ISSUE TITLE
Add data context to documentation

### ISSUE THREAD

**Issue by EOstridge** [department-for-transport-BODS/bods-data-extractor#60]
**Is your feature request related to a problem? Please describe.**

As a data consumer, I would like there to be better context for the data this package returns. 

**Describe the solution you'd like**

It would be useful if there was a glossary of terms or data dictionary created to provide this additional context in an easy-to-access place. 

Example: 
NOCs - NOC stands for National Operator Code. Each bus operator has its own identifying code, consisting of four letters. To find the NOC for the operators you are interested in, _follow these steps._ (Also, consider whether BDE can offer a service where user can check what the code for an operator is, if that's helpful).

ATCO (Association of Transport Co-ordinating Officers) codes refer to the unique identifiers used for individual UK bus stops. The first 3 numbers denote the authority responsible for the stop. The fourth character is a 0 (zero). The remaining characters to a maximum of 8 are alpha-numeric determined locally BODS Data Extractor allows you to filter results on the ATCO admin authority (the first 3 numbers). See fine-tuning section below for more detail on how to do this.

**Comment by lldwork** [comment]
Please see the BODS data catalogue for relevant field definitions - can just include a link potentially

**Comment by lldwork** [comment]
include or link to this set of docs where possible https://data.bus-data.dft.gov.uk/guidance/requirements/?section=casestudies

**Comment by EOstridge** [comment]
Created pull request for glossary
