### ISSUE TITLE
Add high level overview of concepts, data and relationships to documentation (diagram)

### ISSUE THREAD

**Issue by EOstridge** [department-for-transport-BODS/bods-data-extractor#62]
**Is your feature request related to a problem? Please describe.**

As a data consumer, I would like to be able to understand the structure of the data being queried and returned.

**Describe the solution you'd like**

It would be useful if there was a diagram to help visualise the concepts, data and relationships encountered with this package.

**Comment by adamakram1** [comment]
@spencer-b-318 Create a more detailed diagram

**Comment by spencer-b-318** [comment]
![Image](https://user-images.githubusercontent.com/105863784/216959832-8e6fab8d-6acb-431d-85b6-360e0041dc6c.jpg)

CFDS for inspiration

**Comment by adamakram1** [comment]
Shown in FAQ
