### ISSUE TITLE
Provide more context and clarify wording regarding OTC database

### ISSUE THREAD

**Issue by EOstridge** [department-for-transport-BODS/bods-data-extractor#68]
**Is your feature request related to a problem? Please describe.**

As a data consumer, it would be helpful to have a greater explanation of the OTC database and how this relates to the package and BODS. 

**Describe the solution you'd like**

An explanation of what the OTC database is, what OTC stands for and how this relates to BODS. 
Clarification on the meaning of this sentence: "This code is executed automatically when calling a reporting function that requires the OTC database" would also be useful.

**Comment by adamakram1** [comment]
The package is also able to pull the latest copy of the Office for the Traffic Commissioner (OTC) Database

**Comment by adamakram1** [comment]
Linked to documentation Ticket

**Comment by EOstridge** [comment]
Completed with other documentation work - see Glossary of Terms
